GHA: Fix release task workflow

diff --git a/.github/actions/assign-release-task/action.yml b/.github/actions/assign-release-task/action.yml
--- a/.github/actions/assign-release-task/action.yml
+++ b/.github/actions/assign-release-task/action.yml
@@ -42,30 +42,30 @@ runs:
           echo "task_id=$task_id" >> $GITHUB_OUTPUT
         fi
       
-        asana_user_id=$(grep -E "^$username: " .github/actions/assign-release-task/github_asana_mapping.yml | awk -F': ' '{print $2}' | tr -d '"')
-
-        if [ -z "asana_user_id" ]; then
-          echo "User $username not found."
-          exit 1
-        else
-          echo "User ID for $username: $asana_user_id"            
-        fi
-        
-        echo "Assigning task ID $task_id to user ID $asana_user_id"
-
-        # Assign the task to the user
-        response=$(curl -s -X PUT "https://app.asana.com/api/1.0/tasks/${task_id}" \
-          -H "Authorization: Bearer ${asana_token}" \
-          -H "Content-Type: application/json" \
-          -d "{\"data\": {\"assignee\": \"${asana_user_id}\"}}")            
-
-        # Check if the assignment was successful
-        status=$(echo $response | jq -r '.errors')
-
-        if [ "$status" == "null" ]; then
-          echo "Task $task_id successfully assigned to user $asana_user_id."                
-        else
-          echo "Failed to assign task: $status"
-          exit 1
-        fi
+#        asana_user_id=$(grep -E "^$username: " .github/actions/assign-release-task/github_asana_mapping.yml | awk -F': ' '{print $2}' | tr -d '"')
+#
+#        if [ -z "asana_user_id" ]; then
+#          echo "User $username not found."
+#          exit 1
+#        else
+#          echo "User ID for $username: $asana_user_id"
+#        fi
+#
+#        echo "Assigning task ID $task_id to user ID $asana_user_id"
+#
+#        # Assign the task to the user
+#        response=$(curl -s -X PUT "https://app.asana.com/api/1.0/tasks/${task_id}" \
+#          -H "Authorization: Bearer ${asana_token}" \
+#          -H "Content-Type: application/json" \
+#          -d "{\"data\": {\"assignee\": \"${asana_user_id}\"}}")
+#
+#        # Check if the assignment was successful
+#        status=$(echo $response | jq -r '.errors')
+#
+#        if [ "$status" == "null" ]; then
+#          echo "Task $task_id successfully assigned to user $asana_user_id."
+#        else
+#          echo "Failed to assign task: $status"
+#          exit 1
+#        fi
         
