add value check for input parameter

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -1,60 +1,63 @@
-name: Docs
+name: Create Android App Release Task
 
 on:
-  push:
-    branches: ["develop"]
-
   workflow_dispatch:
+    inputs:
+      app-version:
+        description: 'App Version for Release'
+        required: true
+        default: 'PLACEHOLDER'
 
-# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
-permissions:
-  contents: read
-  pages: write
-  id-token: write
+env:
+  ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}
 
-# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
-# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
-  group: "pages"
-  cancel-in-progress: false
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
-  # Single deploy job since we're just deploying
-  deploy:
-    environment:
-      name: github-pages
-      url: ${{ steps.deployment.outputs.page_url }}
-    runs-on: ubuntu-latest
+  create_release_task:
+    name: Create Android App Release Task in Asana
+    runs-on: macos-latest
+
     steps:
-      - name: Checkout
+      - name: Checkout repository
         uses: actions/checkout@v4
-        with:
-          submodules: recursive
 
-      - name: Set up JDK 17
-        uses: actions/setup-java@v4
-        with:
-          java-version: '17'
-          distribution: 'adopt'
-
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v3
-
-      - name: Execute Gradle build
-        run: ./gradlew dokkaHtmlMultiModule
-
-      - name: Copy files
+      - name: Check app-version value
         run: |
-          mkdir -p docs
-          mv build/dokka/htmlMultiModule/* docs
+          if [ "${{ github.event.inputs.app-version }}" == "PLACEHOLDER" ]; then
+            echo "Input value cannot be 'PLACEHOLDER'."
+            exit 1
+          else
+            echo "Input value is valid: ${{ github.event.inputs.app-version }}"
+          fi
 
-      - name: Setup Pages
-        uses: actions/configure-pages@v3
+      - name: Install Release Bridge from Homebrew
+        run: |
+          brew tap cdrussell/aarb
+          brew install aarb
 
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v2
+      - name: Create task in Asana
+        run: |
+          AndroidAsanaBridge version=${{ github.event.inputs.app-version }} action=createRelease,tagPendingTasks,addLinksToDescription,removePendingTasks
+
+      - name: Assign task to Github Actor
+        id: assign-release-task
+        uses: ./.github/actions/assign-release-task
         with:
-          path: 'docs'
-      - name: Deploy to GitHub Pages
-        id: deployment
-        uses: actions/deploy-pages@v2
+          task_name: 'Android Release ${{ github.event.inputs.app-version }}'
+          asana_token: ${{ secrets.GH_ASANA_SECRET }}
+          project_gid: ${{ vars.GH_ANDROID_RELEASE_BOARD_PROJECT_ID }}
+          username: ${{ github.actor }}
+
+      - name: Create Asana task when workflow failed
+        if: ${{ failure() }}
+        uses: duckduckgo/native-github-asana-sync@v1.1
+        with:
+          asana-pat: ${{ secrets.GH_ASANA_SECRET }}
+          asana-project: ${{ vars.GH_ANDROID_APP_PROJECT_ID }}
+          asana-section: ${{ vars.GH_ANDROID_APP_INCOMING_SECTION_ID }}
+          asana-task-name: GH Workflow Failure - Create Android App Release Task
+          asana-task-description: The Create Android App Release Task workflow has failed. See https://github.com/duckduckgo/Android/actions/runs/${{ github.run_id }}
+          action: 'create-asana-task'
diff --git a/.github/workflows/release_create_task.yml b/.github/workflows/release_create_task.yml
--- a/.github/workflows/release_create_task.yml
+++ b/.github/workflows/release_create_task.yml
@@ -6,7 +6,7 @@ on:
       app-version:
         description: 'App Version for Release'
         required: true
-        default: '5.215.0'
+        default: 'PLACEHOLDER'
 
 env:
   ASANA_PAT: ${{ secrets.GH_ASANA_SECRET }}
@@ -23,6 +23,15 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Check app-version value
+        run: |
+          if [ "${{ github.event.inputs.app-version }}" == "PLACEHOLDER" ]; then
+            echo "Input value cannot be 'PLACEHOLDER'."
+            exit 1
+          else
+            echo "Input value is valid: ${{ github.event.inputs.app-version }}"
+          fi
 
       - name: Install Release Bridge from Homebrew
         run: |
