using new parsing

diff --git a/.github/workflows/docs.yml b/.github/workflows/docs.yml
--- a/.github/workflows/docs.yml
+++ b/.github/workflows/docs.yml
@@ -43,14 +43,18 @@ jobs:
         id: get-asana-user-id
         shell: bash
         run: |
-          echo "Finding Asana User Id for ${{ github.actor }}"
-          user_id="$(yq ."${{ github.actor }}" ./.github/github_asana_mapping.yml)"
-          if [[ -z "$user_id" || "$user_id" == "null" ]]; then
-            echo "Asana User ID not found for GitHub handle: ${{ github.actor }}"
+          username="${{ github.actor }}"
+          user_id=$(grep -E "^$username: " github_asana_mapping.yml | awk -F': ' '{print $2}' | tr -d '"')
+
+          if [ -z "$user_id" ]; then
+            echo "User $username not found."
+            exit 1
           else
-            echo "Asana User ID found for GitHub handle: ${{ github.actor }} is ${{user_id}}"
-            echo "{user-id}=${user_id}" >> $GITHUB_OUTPUT        
+            echo "User ID for $username: $user_id"
+            echo "user_id=$user_id" >> $GITHUB_ENV
+            echo "::set-output name=asana-user-id::$user_id"
+#            echo "{asana-user-id}=${user_id}" >> $GITHUB_OUTPUT
           fi
       - name: Show Asana User Id
         run: |
-          echo "The output from the script is: ${{ steps.get-asana-user-id.outputs.user-id }}"
+          echo "The output from the script is: ${{ steps.get-asana-user-id.outputs.asana-user-id }}"
