fail on pixel lint instead of commiting fix

diff --git a/.github/workflows/pixel_validation.yml b/.github/workflows/pixel_validation.yml
--- a/.github/workflows/pixel_validation.yml
+++ b/.github/workflows/pixel_validation.yml
@@ -37,28 +37,9 @@ jobs:
               run: npm ci --verbose
               working-directory: PixelDefinitions
 
-            # Lint step for push (fail on error), for PRs run fix instead
-            - name: Check or Fix lint
-              id: lint
-              run: |
-                if [[ "${{ github.event_name }}" == "pull_request" ]]; then
-                  npm run lint.fix || true
-                else
-                  npm run lint
-                fi
+            - name: Lint
+              run: npm run lint || (npm run lint.fix; git diff; echo 'Pixel lint check failed, review diff above or run "npm run lint.fix"'; exit 1)
               working-directory: PixelDefinitions
-
-            # Commit and push changes if lint.fix was run and made changes
-            - name: Commit and push linter fixes (PRs only)
-              if: github.event_name == 'pull_request'
-              run: |
-                git config --global user.name "github-actions[bot]"
-                git config --global user.email "github-actions[bot]@users.noreply.github.com"
-                git add PixelDefinitions/
-                if ! git diff --cached --quiet; then
-                  git commit -m "chore: auto-fix lint errors"
-                  git push
-                fi
 
             - name: Run pixel validation
               run: npm run validate-defs-without-formatting -- -g ../internal-github-asana-utils/user_map.yml
